BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Roles";
CREATE TABLE IF NOT EXISTS "Roles" (
	"ID"	INTEGER,
	"RoleName"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Users";
CREATE TABLE IF NOT EXISTS "Users" (
	"ID"	INTEGER,
	"Username"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL,
	"GivenName"	TEXT NOT NULL,
	"Surname"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "UserRoles";
CREATE TABLE IF NOT EXISTS "UserRoles" (
	"ID"	INTEGER,
	"UserID"	INTEGER NOT NULL,
	"RoleID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("RoleID") REFERENCES "Roles"("ID"),
	FOREIGN KEY("UserID") REFERENCES "Users"("ID")
);
DROP TABLE IF EXISTS "InventoryCategories";
CREATE TABLE IF NOT EXISTS "InventoryCategories" (
	"ID"	INTEGER,
	"CategoryName"	TEXT NOT NULL,
	"CategoryDescription"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Inventory";
CREATE TABLE IF NOT EXISTS "Inventory" (
	"ID"	INTEGER,
	"ItemCategory"	INTEGER NOT NULL,
	"ItemName"	TEXT NOT NULL,
	"ItemDescription"	TEXT,
	"ItemPrice"	NUMERIC NOT NULL DEFAULT 0,
	"StockLevel"	NUMERIC NOT NULL DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ItemCategory") REFERENCES "InventoryCategories"("ID")
);
DROP TABLE IF EXISTS "Sales";
CREATE TABLE IF NOT EXISTS "Sales" (
	"ID"	INTEGER,
	"CashierID"	INTEGER NOT NULL,
	"DatetimeOfPurchase"	TEXT NOT NULL,
	"Voided"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("CashierID") REFERENCES "Users"("ID")
);
DROP TABLE IF EXISTS "SalesItems";
CREATE TABLE IF NOT EXISTS "SalesItems" (
	"ID"	INTEGER,
	"SaleID"	INTEGER NOT NULL,
	"InventoryID"	INTEGER NOT NULL,
	"ItemQuantity"	INTEGER NOT NULL,
	"TimeOfSalePrice"	NUMERIC NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("SaleID") REFERENCES "Sales"("ID"),
	FOREIGN KEY("InventoryID") REFERENCES "Inventory"("ID")
);
COMMIT;
